<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.1.14.2 setup script
 * Date: Mon, 28 Jul 2014 09:12:56 +0000
 */

$cfg['DefaultLang'] = 'ja';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>

