---
- name: Install wp-cli.phar
  get_url:
    url=https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    dest=/usr/local/bin/wp
    mode=755

- name: Make Directory
  command: chdir=/home/vagrant /bin/mkdir .wp-cli

- name: Copy wp-cli configure file
  copy:
    src=config.yml
    dest=/home/vagrant/.wp-cli/
    group=vagrant
    owner=vagrant
